import HeroContentLeft from '@/components/HeroContentLeft';
import { createStyles, Overlay, Container, Title, Button, Text, rem } from '@mantine/core';
import Head from 'next/head';

function Home() {

  return (
    <>
      <Head>
        <title>inkX</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
    <HeroContentLeft />
    </>
  );
}

export default Home;